// Generated by CoffeeScript 1.10.0
var assert;

assert = chai.assert;

describe("Game test", function() {
  return beforeEach(function() {
    var a, deal, deck, hand;
    deck = new Deck();
    hand = deck.dealPlayer();
    deal = deck.dealDealer();
    return a = hand.scores()[0];
  });
});
